/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IBattleshipGame, IBattleshipGameInterface } from "../../../contracts/battleship/IBattleshipGame";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "Joined",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_by",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_nonce",
        type: "uint256",
      },
    ],
    name: "Left",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bool",
        name: "hit",
        type: "bool",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
    ],
    name: "Report",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_x",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_y",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
    ],
    name: "Shot",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_by",
        type: "address",
      },
    ],
    name: "Started",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_winner",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_nonce",
        type: "uint256",
      },
    ],
    name: "Won",
    type: "event",
  },
  {
    inputs: [],
    name: "HIT_MAX",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
      {
        internalType: "uint256[2]",
        name: "_shot",
        type: "uint256[2]",
      },
    ],
    name: "firstTurn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "gameIndex",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
    ],
    name: "gameState",
    outputs: [
      {
        internalType: "address[2]",
        name: "_participants",
        type: "address[2]",
      },
      {
        internalType: "bytes32[2]",
        name: "_boards",
        type: "bytes32[2]",
      },
      {
        internalType: "uint256",
        name: "_turnNonce",
        type: "uint256",
      },
      {
        internalType: "uint256[2]",
        name: "_hitNonce",
        type: "uint256[2]",
      },
      {
        internalType: "enum IBattleshipGame.GameStatus",
        name: "_status",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "_winner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "games",
    outputs: [
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "enum IBattleshipGame.GameStatus",
        name: "status",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "winner",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "joinGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
    ],
    name: "leaveGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "newGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "playing",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "trustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_game",
        type: "uint256",
      },
      {
        internalType: "uint256[2]",
        name: "_next",
        type: "uint256[2]",
      },
      {
        internalType: "bytes",
        name: "_proof",
        type: "bytes",
      },
    ],
    name: "turn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBattleshipGame__factory {
  static readonly abi = _abi;
  static createInterface(): IBattleshipGameInterface {
    return new Interface(_abi) as IBattleshipGameInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBattleshipGame {
    return new Contract(address, _abi, runner) as unknown as IBattleshipGame;
  }
}
