/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  I_xor2_verifier,
  I_xor2_verifierInterface,
} from "../../../../contracts/verifierWrappers/xor2_verifier_wrapper.sol/I_xor2_verifier";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[2]",
        name: "a",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[2][2]",
        name: "b",
        type: "uint256[2][2]",
      },
      {
        internalType: "uint256[2]",
        name: "c",
        type: "uint256[2]",
      },
      {
        internalType: "uint256[1]",
        name: "input",
        type: "uint256[1]",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class I_xor2_verifier__factory {
  static readonly abi = _abi;
  static createInterface(): I_xor2_verifierInterface {
    return new Interface(_abi) as I_xor2_verifierInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): I_xor2_verifier {
    return new Contract(address, _abi, runner) as unknown as I_xor2_verifier;
  }
}
