/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { INativeStakingReward, INativeStakingRewardInterface } from "../../../../contracts/interfaces/staking/INativeStakingReward";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "address",
        name: "_prover",
        type: "address",
      },
    ],
    name: "onClaimReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "onSlash",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "address",
        name: "_stakeToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_prover",
        type: "address",
      },
    ],
    name: "onStakeUpdate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_stakingPool",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_isSupported",
        type: "bool",
      },
    ],
    name: "setStakeToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "address",
        name: "_stakeToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_prover",
        type: "address",
      },
    ],
    name: "update",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_stakeToken",
        type: "address",
      },
      {
        internalType: "address",
        name: "_prover",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_rewardAmount",
        type: "uint256",
      },
    ],
    name: "updateFeeReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_prover",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_rewardAmount",
        type: "uint256",
      },
    ],
    name: "updateInflationReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INativeStakingReward__factory {
  static readonly abi = _abi;
  static createInterface(): INativeStakingRewardInterface {
    return new Interface(_abi) as INativeStakingRewardInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INativeStakingReward {
    return new Contract(address, _abi, runner) as unknown as INativeStakingReward;
  }
}
