/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Battleship_board_wrapper } from "./Battleship_board_wrapper";
export type { Battleship_shot_wrapper } from "./Battleship_shot_wrapper";
