/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iVerifierSol from "./IVerifier.sol";
export type { iVerifierSol };
import type * as plonkVkSol from "./plonk_vk.sol";
export type { plonkVkSol };
import type * as transferVerifierSol from "./transfer_verifier.sol";
export type { transferVerifierSol };
import type * as verifierXor2Sol from "./verifier_xor2.sol";
export type { verifierXor2Sol };
import type * as zkbVerifierSol from "./zkb_verifier.sol";
export type { zkbVerifierSol };
import type * as zksyncVerifierSol from "./zksync_verifier.sol";
export type { zksyncVerifierSol };
