/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../../common";

export interface INativeStakingRewardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "onClaimReward"
      | "onSlash"
      | "onStakeUpdate"
      | "setStakeToken"
      | "update"
      | "updateFeeReward"
      | "updateInflationReward",
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "onClaimReward", values: [AddressLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "onSlash", values?: undefined): string;
  encodeFunctionData(functionFragment: "onStakeUpdate", values: [AddressLike, AddressLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "setStakeToken", values: [AddressLike, boolean]): string;
  encodeFunctionData(functionFragment: "update", values: [AddressLike, AddressLike, AddressLike]): string;
  encodeFunctionData(functionFragment: "updateFeeReward", values: [AddressLike, AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "updateInflationReward", values: [AddressLike, BigNumberish]): string;

  decodeFunctionResult(functionFragment: "onClaimReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onSlash", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onStakeUpdate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setStakeToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateFeeReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateInflationReward", data: BytesLike): Result;
}

export interface INativeStakingReward extends BaseContract {
  connect(runner?: ContractRunner | null): INativeStakingReward;
  waitForDeployment(): Promise<this>;

  interface: INativeStakingRewardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  onClaimReward: TypedContractMethod<[_account: AddressLike, _prover: AddressLike], [void], "nonpayable">;

  onSlash: TypedContractMethod<[], [void], "nonpayable">;

  onStakeUpdate: TypedContractMethod<[_account: AddressLike, _stakeToken: AddressLike, _prover: AddressLike], [void], "nonpayable">;

  setStakeToken: TypedContractMethod<[_stakingPool: AddressLike, _isSupported: boolean], [void], "nonpayable">;

  update: TypedContractMethod<[account: AddressLike, _stakeToken: AddressLike, _prover: AddressLike], [void], "nonpayable">;

  updateFeeReward: TypedContractMethod<[_stakeToken: AddressLike, _prover: AddressLike, _rewardAmount: BigNumberish], [void], "nonpayable">;

  updateInflationReward: TypedContractMethod<[_prover: AddressLike, _rewardAmount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "onClaimReward"): TypedContractMethod<[_account: AddressLike, _prover: AddressLike], [void], "nonpayable">;
  getFunction(nameOrSignature: "onSlash"): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "onStakeUpdate",
  ): TypedContractMethod<[_account: AddressLike, _stakeToken: AddressLike, _prover: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakeToken",
  ): TypedContractMethod<[_stakingPool: AddressLike, _isSupported: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "update",
  ): TypedContractMethod<[account: AddressLike, _stakeToken: AddressLike, _prover: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeeReward",
  ): TypedContractMethod<[_stakeToken: AddressLike, _prover: AddressLike, _rewardAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateInflationReward",
  ): TypedContractMethod<[_prover: AddressLike, _rewardAmount: BigNumberish], [void], "nonpayable">;

  filters: {};
}
