/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iVerifierSol from "./IVerifier.sol";
export type { iVerifierSol };
import type * as wrappers from "./wrappers";
export type { wrappers };
export type { BattleshipGame } from "./BattleshipGame";
export type { BoardVerifier } from "./BoardVerifier";
export type { Forwarder } from "./Forwarder";
export type { IBattleshipGame } from "./IBattleshipGame";
export type { ShotVerifier } from "./ShotVerifier";
