/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBoardVerifier__factory } from "./IBoardVerifier__factory";
export { IShotVerifier__factory } from "./IShotVerifier__factory";
