/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { I_xor2_verifier } from "./I_xor2_verifier";
export type { Xor2_verifier_wrapper } from "./Xor2_verifier_wrapper";
